In [1]:
print("bahar")

bahar


_deneme_ **markdown**

# Numpya Giris

In [31]:
import numpy as np

In [4]:
a = np.array ([1,2,3])
b = np.array ([3,4,5])

In [5]:
a*b

array([ 3,  8, 15])

## Numpy Array Olusturmak

In [6]:
import numpy as np

In [9]:
a = np.array([2,3,6])

In [10]:
type(a)

numpy.ndarray

In [11]:
np.array ([4,5,6] , dtype = float)

array([4., 5., 6.])

In [12]:
#sifirdan array olusturma

In [14]:
np.zeros ([10] , dtype= int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [25]:
np.ones ([2,2] , dtype=int)

array([[1, 1],
       [1, 1]])

In [26]:
np.full([2,1] , 3.5)

array([[3.5],
       [3.5]])

In [20]:
np.arange (0,10,2) #0ile 10arasinda 2ser artan dizi olustur

array([0, 2, 4, 6, 8])

In [28]:
np.linspace(0,5,10) #0ile 1arasinda tek boyutlu 10sayi olusturur

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [29]:
np.random.normal (10,4, (2,3)) #ort10 standarsapma4 olan 3e 4luk matris olustur

array([[ 8.64971789, 12.43910587, 15.4986801 ],
       [12.65254204,  7.29815389, 12.27632417]])

In [24]:
np.random.randint(0,10, (3,3)) #0 10arası 3e3 rand sayilarla matris

array([[5, 6, 6],
       [0, 9, 2],
       [1, 7, 4]])

In [35]:
b= np.random.randint(10, size = (3,2))

In [37]:
b

array([[2, 4],
       [3, 2],
       [3, 9]])

In [36]:
b.ndim

2

In [38]:
b.size

6

In [40]:
b.shape

(3, 2)

In [41]:
b.dtype

dtype('int32')

### RESHAPE

In [42]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
np.arange(0,10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [45]:
a = np.arange(0,10)

In [46]:
a.ndim

1

In [47]:
b= np.arange(0,10).reshape(2,5)

In [48]:
b.ndim

2

In [53]:
c= np.arange(0,10).reshape(1,10)
c

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [52]:
c.ndim

2

In [54]:
c.shape

(1, 10)

### CONCATENATE

In [55]:
a = np.array([1,2,3])

In [56]:
b = np.array([4,5,6])

In [58]:
np.concatenate([a,b])

array([1, 2, 3, 4, 5, 6])

In [64]:
a = np.random.randint(0,10, (3,2))

In [65]:
a

array([[2, 1],
       [7, 5],
       [2, 3]])

In [66]:
np.concatenate([a,a]) #altalta satir bazinda birlestirdi

array([[2, 1],
       [7, 5],
       [2, 3],
       [2, 1],
       [7, 5],
       [2, 3]])

In [67]:
np.concatenate([a,a] , axis=1) #sutun bazinda birlesim

array([[2, 1, 2, 1],
       [7, 5, 7, 5],
       [2, 3, 2, 3]])

### SPLIT

In [72]:
x = np.array([1,2,3,99,99,3,2,1])

In [76]:
np.split(x, [3,5])

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [78]:
a,b,c = np.split(x, [3,5])
a

array([1, 2, 3])

In [79]:
#iki boyutlu ayirma

In [85]:
m = np.arange(16).reshape(4,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [87]:
ust , alt = np.vsplit(m,[2]) #yatay bolme

In [88]:
ust

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [89]:
alt

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [91]:
sol , sag = np.hsplit(m,[2])

In [92]:
sol

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [93]:
sag

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

### SORT

In [94]:
v = np.array([2,5,7,6,1,3])

In [95]:
np.sort(v)

array([1, 2, 3, 5, 6, 7])

In [97]:
#iki boyutlu siralama

In [100]:
m = np.random.normal(20,5, (3,3))

In [101]:
m

array([[19.14195499, 24.96018741, 16.30243047],
       [16.36276855, 13.17508607, 23.5060897 ],
       [27.00320693,  7.64710617, 24.36359655]])

In [105]:
np.sort(m , axis=1) #satirlari kendi icinde kucukten buyuge siralar

array([[16.30243047, 19.14195499, 24.96018741],
       [13.17508607, 16.36276855, 23.5060897 ],
       [ 7.64710617, 24.36359655, 27.00320693]])

In [106]:
np.sort(m , axis=0) #sutunlari kendi icinde kucukten buyuge siralar

array([[16.36276855,  7.64710617, 16.30243047],
       [19.14195499, 13.17508607, 23.5060897 ],
       [27.00320693, 24.96018741, 24.36359655]])

### Elemanlara ulasma tek boyutta

In [2]:
import numpy as np

In [14]:
m = np.random.randint(10, size= (3,5))

In [15]:
m

array([[2, 6, 7, 2, 8],
       [4, 0, 2, 7, 5],
       [8, 8, 5, 0, 3]])

In [16]:
m [1,2]

2

In [18]:
m[1,2]= 666
m

array([[  2,   6,   7,   2,   8],
       [  4,   0, 666,   7,   5],
       [  8,   8,   5,   0,   3]])

In [19]:
a= np.arange (20,30)

In [20]:
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [21]:
a[:3]

array([20, 21, 22])

In [22]:
a[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [24]:
a[1::2] #1den sona 2ser aralıklı alarak

array([21, 23, 25, 27, 29])

In [25]:
a[0::3]

array([20, 23, 26, 29])

### SLICING alt kumeye erisme

In [26]:
m= np.random.randint(10, size= (5,5))

In [27]:
m

array([[0, 3, 4, 9, 2],
       [2, 9, 5, 7, 7],
       [3, 9, 3, 7, 0],
       [7, 8, 3, 7, 4],
       [6, 8, 6, 6, 1]])

In [29]:
m[:,0] #tum satırları al 0.sutunu al

array([0, 2, 3, 7, 6])

In [31]:
m[0,:] #tum sutunları al 0.satırı al

array([0, 3, 4, 9, 2])

In [33]:
m[0:2,0:3] #0dan 2ye kadar olan satırları ve 0dan 3e kadar olan sutunları al

array([[0, 3, 4],
       [2, 9, 5]])

In [35]:
m[::,0:2] #tum satırları aldı 0dan 2ye sutunları al

array([[0, 3],
       [2, 9],
       [3, 9],
       [7, 8],
       [6, 8]])

In [49]:
alt_a = m[1:3,0:2].copy() #copy sayesinde alt kume ana arrayden bagimsiz yapildi
alt_a

array([[2, 9],
       [3, 9]])

In [46]:
alt_a [0,0] = 999

In [47]:
alt_a

array([[999,   9],
       [  3,   9]])

In [48]:
m

array([[0, 3, 4, 9, 2],
       [2, 9, 5, 7, 7],
       [3, 9, 3, 7, 0],
       [7, 8, 3, 7, 4],
       [6, 8, 6, 6, 1]])

### FANCY INDEX ILE ELEMANA ERISMEK

In [50]:
v = np.arange(0,30,3)

In [51]:
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [52]:
getir= [1,3,5] 

In [55]:
v[getir] #fancy index kullanmis olduk

array([ 3,  9, 15])

### iki boyutta fancy

In [56]:
m = np.arange(9).reshape(3,3)

In [57]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [58]:
satir= np.array([0,1])

In [59]:
sutun = np.array([1,2])

In [60]:
m[satir,sutun]

array([1, 5])

In [61]:
#slice ile fancy

In [62]:
m[0:,[1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [63]:
m[0,[1,2]] #basit indexle fancy

array([1, 2])

In [64]:
m[1,2]

5

In [65]:
v = np.array([1,2,3,4,5])

In [66]:
v<3

array([ True,  True, False, False, False])

In [67]:
v[v>=3]

array([3, 4, 5])

In [68]:
v[v==3]

array([3])

In [69]:
v[v!=3]

array([1, 2, 4, 5])

In [70]:
#ufunc

In [71]:
np.subtract(v,1)

array([0, 1, 2, 3, 4])

In [72]:
np.add(v,5)

array([ 6,  7,  8,  9, 10])

In [73]:
np.divide(v,2)

array([0.5, 1. , 1.5, 2. , 2.5])

In [74]:
np.multiply(v,4)

array([ 4,  8, 12, 16, 20])

In [75]:
np.power(v,3)

array([  1,   8,  27,  64, 125], dtype=int32)

In [76]:
np.mod(v,2)

array([1, 0, 1, 0, 1], dtype=int32)

In [83]:
import numpy as np

In [84]:
np.absolute (np.array [-3])

TypeError: 'builtin_function_or_method' object is not subscriptable

In [85]:
np.sin(360)

0.9589157234143065

In [86]:
np.cos(180)

-0.5984600690578581

In [87]:
np.log(v)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [88]:
np.mean(v)

3.0

In [92]:
#denklem cozumu

5x0+x1=12
x0+3x1=10

In [99]:
a=np.array([[5,1] ,[1,3]])

In [100]:
b=np.array([12,10])

In [101]:
x = np.linalg.solve(a,b)

In [102]:
x

array([1.85714286, 2.71428571])